name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    if: "${{ github.actor != 'github-actions[bot]' }}"
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5.0.0
        with:
          target-branch: main
